### ISSUE TITLE
Video Sitemap is not accordingly placed

### ISSUE THREAD

**Issue by Paul-Riedel** [vimes1984/video_sitemap#1] opened 2015-04-08 13:46 UTC
1) When you run more that one blog (what most professionals do) you can't put a file in home, since one would overwrite the other.
2) Google Sitemap can't reach the file in home because Home is two levels upper the Wordpress directory.
I suggest that you use the wp-content or the nomal home fro word where you can find the index.htm as well

So far the generated file seems to have another issue with germa letters (I assume) ü is in html &uuml; and this combination is not accepted by google sitemap check in the webmaster tools

In case I can help with test, please let me know.

**Comment by vimes1984** [comment] 2015-04-08 14:01
I'm fixing the diretory error now I'll be using: https://codex.wordpress.org/Function_Reference/get_home_path
insterad of $_SERVER['document_root']. 
Can you open up another bug report for the fix on the caracters explaining what the issue is please

**Comment by vimes1984** [comment] 2015-04-08 14:13
OK if you upadte to version 1.2.1 it should fix your issues! 
Please keep me posted 
Chris

**Comment by vimes1984** [comment] 2015-04-08 14:36
seen as we've fixed your error could you please be so kind as to change your reveiw accordingly

**Comment by Paul-Riedel** [comment] 2015-04-08 14:47
hi Dear,

probably you have a slash to much:
/mnt/web4/e1/90/52242690/htdocs/WordPress_03//sitemap-video.xml

Is it?

**Comment by vimes1984** [comment] 2015-04-08 14:48
it shouldn't matter but I'll fix it one min

**Comment by Paul-Riedel** [comment] 2015-04-08 14:49
Double Video title:
Es wurden doppelte Videotitel in Ihrer Sitemap oder Ihrem Feed gefunden. Durch doppelte Titel wird den Nutzern die Erkennung des Videoinhalts erschwert. Gestalten Sie die Titel aussagekräftiger, sodass sie den Inhalt des Videos besser widerspiegeln.

Probably is the description field and the titel mismatched, I see.

**Comment by Paul-Riedel** [comment] 2015-04-08 14:51
I checked the file, but I don't see the error...?

**Comment by Paul-Riedel** [comment] 2015-04-08 14:52
I found. The description has the title again.

**Comment by vimes1984** [comment] 2015-04-08 14:52
it's giving you double title because you don't have a excerpt set up on the post you have the video in so it uses the ttile...
version 1.2.2 should fix the double slash issue

**Comment by Paul-Riedel** [comment] 2015-04-08 14:55
I tried the 1.2.2. the warning with the title in the description is still there. What can I do?

**Comment by vimes1984** [comment] 2015-04-08 14:58
ok we are moving to here: https://github.com/vimes1984/video_sitemap/issues/2
1.2.2 is to fix the double slashes :D if the bug is different new bug report every time :D 
if you could please explain in there what exactly is the issue your experiancing with the title/desc

**Closed as completed by vimes1984** 2015-04-08 14:58 UTC

**Comment by Paul-Riedel** [comment] 2015-04-08 15:01
MOVED TO: https://github.com/vimes1984/video_sitemap/issues/3
